SELECT
    (TO_CHAR(TO_DATE(DELIVERY_DATE), 'YYYY-MM-DD')) AS "orders.delivery_date"
FROM
    OL.ORDERS AS orders
WHERE ((( DELIVERY_DATE ) >= ((CURRENT_DATE())) AND ( DELIVERY_DATE ) < ((DATEADD('day', 1, CURRENT_DATE())))))
GROUP BY
    (TO_DATE(DELIVERY_DATE))
ORDER BY
    1 DESC
